drop policy "Can view own data" on "public"."search";

drop policy "Enable insert for users based on user_id" on "public"."search";

revoke delete on table "public"."search" from "anon";

revoke insert on table "public"."search" from "anon";

revoke references on table "public"."search" from "anon";

revoke select on table "public"."search" from "anon";

revoke trigger on table "public"."search" from "anon";

revoke truncate on table "public"."search" from "anon";

revoke update on table "public"."search" from "anon";

revoke delete on table "public"."search" from "authenticated";

revoke insert on table "public"."search" from "authenticated";

revoke references on table "public"."search" from "authenticated";

revoke select on table "public"."search" from "authenticated";

revoke trigger on table "public"."search" from "authenticated";

revoke truncate on table "public"."search" from "authenticated";

revoke update on table "public"."search" from "authenticated";

revoke delete on table "public"."search" from "service_role";

revoke insert on table "public"."search" from "service_role";

revoke references on table "public"."search" from "service_role";

revoke select on table "public"."search" from "service_role";

revoke trigger on table "public"."search" from "service_role";

revoke truncate on table "public"."search" from "service_role";

revoke update on table "public"."search" from "service_role";

alter table "public"."search" drop constraint "search_broker_id_fkey";

alter table "public"."search" drop constraint "search_profile_id_fkey";

alter table "public"."search" drop constraint "search_user_id_fkey";

alter table "public"."removal" drop constraint "removal_search_id_fkey";

alter table "public"."search" drop constraint "search_pkey";

drop index if exists "public"."search_pkey";

drop table "public"."search";

create table "public"."searches" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile_id" bigint,
    "broker_id" bigint,
    "status" search_status,
    "result" jsonb,
    "user_id" uuid,
    "updated_at" timestamp with time zone default now()
);


alter table "public"."searches" enable row level security;

alter table "public"."google" drop column "result";

alter table "public"."google" add column "results" jsonb;

CREATE UNIQUE INDEX search_pkey ON public.searches USING btree (id);

alter table "public"."searches" add constraint "search_pkey" PRIMARY KEY using index "search_pkey";

alter table "public"."searches" add constraint "search_broker_id_fkey" FOREIGN KEY (broker_id) REFERENCES brokers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."searches" validate constraint "search_broker_id_fkey";

alter table "public"."searches" add constraint "search_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."searches" validate constraint "search_profile_id_fkey";

alter table "public"."searches" add constraint "search_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."searches" validate constraint "search_user_id_fkey";

alter table "public"."removal" add constraint "removal_search_id_fkey" FOREIGN KEY (search_id) REFERENCES searches(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."removal" validate constraint "removal_search_id_fkey";

grant delete on table "public"."searches" to "anon";

grant insert on table "public"."searches" to "anon";

grant references on table "public"."searches" to "anon";

grant select on table "public"."searches" to "anon";

grant trigger on table "public"."searches" to "anon";

grant truncate on table "public"."searches" to "anon";

grant update on table "public"."searches" to "anon";

grant delete on table "public"."searches" to "authenticated";

grant insert on table "public"."searches" to "authenticated";

grant references on table "public"."searches" to "authenticated";

grant select on table "public"."searches" to "authenticated";

grant trigger on table "public"."searches" to "authenticated";

grant truncate on table "public"."searches" to "authenticated";

grant update on table "public"."searches" to "authenticated";

grant delete on table "public"."searches" to "service_role";

grant insert on table "public"."searches" to "service_role";

grant references on table "public"."searches" to "service_role";

grant select on table "public"."searches" to "service_role";

grant trigger on table "public"."searches" to "service_role";

grant truncate on table "public"."searches" to "service_role";

grant update on table "public"."searches" to "service_role";

create policy "Can view own data"
on "public"."searches"
as permissive
for select
to public
using ((auth.uid() = user_id));


create policy "Enable insert for users based on user_id"
on "public"."searches"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = user_id));




