create table "public"."auth_group" (
    "id" integer generated by default as identity not null,
    "name" character varying(150) not null
);


create table "public"."auth_group_permissions" (
    "id" bigint generated by default as identity not null,
    "group_id" integer not null,
    "permission_id" integer not null
);


create table "public"."auth_permission" (
    "id" integer generated by default as identity not null,
    "name" character varying(255) not null,
    "content_type_id" integer not null,
    "codename" character varying(100) not null
);


create table "public"."auth_user" (
    "id" integer generated by default as identity not null,
    "password" character varying(128) not null,
    "last_login" timestamp with time zone,
    "is_superuser" boolean not null,
    "username" character varying(150) not null,
    "first_name" character varying(150) not null,
    "last_name" character varying(150) not null,
    "email" character varying(254) not null,
    "is_staff" boolean not null,
    "is_active" boolean not null,
    "date_joined" timestamp with time zone not null
);


create table "public"."auth_user_groups" (
    "id" bigint generated by default as identity not null,
    "user_id" integer not null,
    "group_id" integer not null
);


create table "public"."auth_user_user_permissions" (
    "id" bigint generated by default as identity not null,
    "user_id" integer not null,
    "permission_id" integer not null
);


create table "public"."django_admin_log" (
    "id" integer generated by default as identity not null,
    "action_time" timestamp with time zone not null,
    "object_id" text,
    "object_repr" character varying(200) not null,
    "action_flag" smallint not null,
    "change_message" text not null,
    "content_type_id" integer,
    "user_id" integer not null
);


create table "public"."django_content_type" (
    "id" integer generated by default as identity not null,
    "app_label" character varying(100) not null,
    "model" character varying(100) not null
);


create table "public"."django_migrations" (
    "id" bigint generated by default as identity not null,
    "app" character varying(255) not null,
    "name" character varying(255) not null,
    "applied" timestamp with time zone not null
);


create table "public"."django_session" (
    "session_key" character varying(40) not null,
    "session_data" text not null,
    "expire_date" timestamp with time zone not null
);


CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);

CREATE UNIQUE INDEX auth_group_name_key ON public.auth_group USING btree (name);

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);

CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON public.auth_group_permissions USING btree (group_id, permission_id);

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);

CREATE UNIQUE INDEX auth_group_permissions_pkey ON public.auth_group_permissions USING btree (id);

CREATE UNIQUE INDEX auth_group_pkey ON public.auth_group USING btree (id);

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);

CREATE UNIQUE INDEX auth_permission_content_type_id_codename_01ab375a_uniq ON public.auth_permission USING btree (content_type_id, codename);

CREATE UNIQUE INDEX auth_permission_pkey ON public.auth_permission USING btree (id);

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);

CREATE UNIQUE INDEX auth_user_groups_pkey ON public.auth_user_groups USING btree (id);

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);

CREATE UNIQUE INDEX auth_user_groups_user_id_group_id_94350c0c_uniq ON public.auth_user_groups USING btree (user_id, group_id);

CREATE UNIQUE INDEX auth_user_pkey ON public.auth_user USING btree (id);

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);

CREATE UNIQUE INDEX auth_user_user_permissions_pkey ON public.auth_user_user_permissions USING btree (id);

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);

CREATE UNIQUE INDEX auth_user_user_permissions_user_id_permission_id_14a6b632_uniq ON public.auth_user_user_permissions USING btree (user_id, permission_id);

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);

CREATE UNIQUE INDEX auth_user_username_key ON public.auth_user USING btree (username);

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);

CREATE UNIQUE INDEX django_admin_log_pkey ON public.django_admin_log USING btree (id);

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);

CREATE UNIQUE INDEX django_content_type_app_label_model_76bd3d3b_uniq ON public.django_content_type USING btree (app_label, model);

CREATE UNIQUE INDEX django_content_type_pkey ON public.django_content_type USING btree (id);

CREATE UNIQUE INDEX django_migrations_pkey ON public.django_migrations USING btree (id);

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);

CREATE UNIQUE INDEX django_session_pkey ON public.django_session USING btree (session_key);

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);

alter table "public"."auth_group" add constraint "auth_group_pkey" PRIMARY KEY using index "auth_group_pkey";

alter table "public"."auth_group_permissions" add constraint "auth_group_permissions_pkey" PRIMARY KEY using index "auth_group_permissions_pkey";

alter table "public"."auth_permission" add constraint "auth_permission_pkey" PRIMARY KEY using index "auth_permission_pkey";

alter table "public"."auth_user" add constraint "auth_user_pkey" PRIMARY KEY using index "auth_user_pkey";

alter table "public"."auth_user_groups" add constraint "auth_user_groups_pkey" PRIMARY KEY using index "auth_user_groups_pkey";

alter table "public"."auth_user_user_permissions" add constraint "auth_user_user_permissions_pkey" PRIMARY KEY using index "auth_user_user_permissions_pkey";

alter table "public"."django_admin_log" add constraint "django_admin_log_pkey" PRIMARY KEY using index "django_admin_log_pkey";

alter table "public"."django_content_type" add constraint "django_content_type_pkey" PRIMARY KEY using index "django_content_type_pkey";

alter table "public"."django_migrations" add constraint "django_migrations_pkey" PRIMARY KEY using index "django_migrations_pkey";

alter table "public"."django_session" add constraint "django_session_pkey" PRIMARY KEY using index "django_session_pkey";

alter table "public"."auth_group" add constraint "auth_group_name_key" UNIQUE using index "auth_group_name_key";

alter table "public"."auth_group_permissions" add constraint "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."auth_group_permissions" validate constraint "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm";

alter table "public"."auth_group_permissions" add constraint "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."auth_group_permissions" validate constraint "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id";

alter table "public"."auth_group_permissions" add constraint "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE using index "auth_group_permissions_group_id_permission_id_0cd325b0_uniq";

alter table "public"."auth_permission" add constraint "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."auth_permission" validate constraint "auth_permission_content_type_id_2f476e4b_fk_django_co";

alter table "public"."auth_permission" add constraint "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE using index "auth_permission_content_type_id_codename_01ab375a_uniq";

alter table "public"."auth_user" add constraint "auth_user_username_key" UNIQUE using index "auth_user_username_key";

alter table "public"."auth_user_groups" add constraint "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."auth_user_groups" validate constraint "auth_user_groups_group_id_97559544_fk_auth_group_id";

alter table "public"."auth_user_groups" add constraint "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."auth_user_groups" validate constraint "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id";

alter table "public"."auth_user_groups" add constraint "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE using index "auth_user_groups_user_id_group_id_94350c0c_uniq";

alter table "public"."auth_user_user_permissions" add constraint "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."auth_user_user_permissions" validate constraint "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm";

alter table "public"."auth_user_user_permissions" add constraint "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."auth_user_user_permissions" validate constraint "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id";

alter table "public"."auth_user_user_permissions" add constraint "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE using index "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq";

alter table "public"."django_admin_log" add constraint "django_admin_log_action_flag_check" CHECK ((action_flag >= 0)) not valid;

alter table "public"."django_admin_log" validate constraint "django_admin_log_action_flag_check";

alter table "public"."django_admin_log" add constraint "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."django_admin_log" validate constraint "django_admin_log_content_type_id_c4bce8eb_fk_django_co";

alter table "public"."django_admin_log" add constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."django_admin_log" validate constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id";

alter table "public"."django_content_type" add constraint "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE using index "django_content_type_app_label_model_76bd3d3b_uniq";

grant delete on table "public"."auth_group" to "anon";

grant insert on table "public"."auth_group" to "anon";

grant references on table "public"."auth_group" to "anon";

grant select on table "public"."auth_group" to "anon";

grant trigger on table "public"."auth_group" to "anon";

grant truncate on table "public"."auth_group" to "anon";

grant update on table "public"."auth_group" to "anon";

grant delete on table "public"."auth_group" to "authenticated";

grant insert on table "public"."auth_group" to "authenticated";

grant references on table "public"."auth_group" to "authenticated";

grant select on table "public"."auth_group" to "authenticated";

grant trigger on table "public"."auth_group" to "authenticated";

grant truncate on table "public"."auth_group" to "authenticated";

grant update on table "public"."auth_group" to "authenticated";

grant delete on table "public"."auth_group" to "service_role";

grant insert on table "public"."auth_group" to "service_role";

grant references on table "public"."auth_group" to "service_role";

grant select on table "public"."auth_group" to "service_role";

grant trigger on table "public"."auth_group" to "service_role";

grant truncate on table "public"."auth_group" to "service_role";

grant update on table "public"."auth_group" to "service_role";

grant delete on table "public"."auth_group_permissions" to "anon";

grant insert on table "public"."auth_group_permissions" to "anon";

grant references on table "public"."auth_group_permissions" to "anon";

grant select on table "public"."auth_group_permissions" to "anon";

grant trigger on table "public"."auth_group_permissions" to "anon";

grant truncate on table "public"."auth_group_permissions" to "anon";

grant update on table "public"."auth_group_permissions" to "anon";

grant delete on table "public"."auth_group_permissions" to "authenticated";

grant insert on table "public"."auth_group_permissions" to "authenticated";

grant references on table "public"."auth_group_permissions" to "authenticated";

grant select on table "public"."auth_group_permissions" to "authenticated";

grant trigger on table "public"."auth_group_permissions" to "authenticated";

grant truncate on table "public"."auth_group_permissions" to "authenticated";

grant update on table "public"."auth_group_permissions" to "authenticated";

grant delete on table "public"."auth_group_permissions" to "service_role";

grant insert on table "public"."auth_group_permissions" to "service_role";

grant references on table "public"."auth_group_permissions" to "service_role";

grant select on table "public"."auth_group_permissions" to "service_role";

grant trigger on table "public"."auth_group_permissions" to "service_role";

grant truncate on table "public"."auth_group_permissions" to "service_role";

grant update on table "public"."auth_group_permissions" to "service_role";

grant delete on table "public"."auth_permission" to "anon";

grant insert on table "public"."auth_permission" to "anon";

grant references on table "public"."auth_permission" to "anon";

grant select on table "public"."auth_permission" to "anon";

grant trigger on table "public"."auth_permission" to "anon";

grant truncate on table "public"."auth_permission" to "anon";

grant update on table "public"."auth_permission" to "anon";

grant delete on table "public"."auth_permission" to "authenticated";

grant insert on table "public"."auth_permission" to "authenticated";

grant references on table "public"."auth_permission" to "authenticated";

grant select on table "public"."auth_permission" to "authenticated";

grant trigger on table "public"."auth_permission" to "authenticated";

grant truncate on table "public"."auth_permission" to "authenticated";

grant update on table "public"."auth_permission" to "authenticated";

grant delete on table "public"."auth_permission" to "service_role";

grant insert on table "public"."auth_permission" to "service_role";

grant references on table "public"."auth_permission" to "service_role";

grant select on table "public"."auth_permission" to "service_role";

grant trigger on table "public"."auth_permission" to "service_role";

grant truncate on table "public"."auth_permission" to "service_role";

grant update on table "public"."auth_permission" to "service_role";

grant delete on table "public"."auth_user" to "anon";

grant insert on table "public"."auth_user" to "anon";

grant references on table "public"."auth_user" to "anon";

grant select on table "public"."auth_user" to "anon";

grant trigger on table "public"."auth_user" to "anon";

grant truncate on table "public"."auth_user" to "anon";

grant update on table "public"."auth_user" to "anon";

grant delete on table "public"."auth_user" to "authenticated";

grant insert on table "public"."auth_user" to "authenticated";

grant references on table "public"."auth_user" to "authenticated";

grant select on table "public"."auth_user" to "authenticated";

grant trigger on table "public"."auth_user" to "authenticated";

grant truncate on table "public"."auth_user" to "authenticated";

grant update on table "public"."auth_user" to "authenticated";

grant delete on table "public"."auth_user" to "service_role";

grant insert on table "public"."auth_user" to "service_role";

grant references on table "public"."auth_user" to "service_role";

grant select on table "public"."auth_user" to "service_role";

grant trigger on table "public"."auth_user" to "service_role";

grant truncate on table "public"."auth_user" to "service_role";

grant update on table "public"."auth_user" to "service_role";

grant delete on table "public"."auth_user_groups" to "anon";

grant insert on table "public"."auth_user_groups" to "anon";

grant references on table "public"."auth_user_groups" to "anon";

grant select on table "public"."auth_user_groups" to "anon";

grant trigger on table "public"."auth_user_groups" to "anon";

grant truncate on table "public"."auth_user_groups" to "anon";

grant update on table "public"."auth_user_groups" to "anon";

grant delete on table "public"."auth_user_groups" to "authenticated";

grant insert on table "public"."auth_user_groups" to "authenticated";

grant references on table "public"."auth_user_groups" to "authenticated";

grant select on table "public"."auth_user_groups" to "authenticated";

grant trigger on table "public"."auth_user_groups" to "authenticated";

grant truncate on table "public"."auth_user_groups" to "authenticated";

grant update on table "public"."auth_user_groups" to "authenticated";

grant delete on table "public"."auth_user_groups" to "service_role";

grant insert on table "public"."auth_user_groups" to "service_role";

grant references on table "public"."auth_user_groups" to "service_role";

grant select on table "public"."auth_user_groups" to "service_role";

grant trigger on table "public"."auth_user_groups" to "service_role";

grant truncate on table "public"."auth_user_groups" to "service_role";

grant update on table "public"."auth_user_groups" to "service_role";

grant delete on table "public"."auth_user_user_permissions" to "anon";

grant insert on table "public"."auth_user_user_permissions" to "anon";

grant references on table "public"."auth_user_user_permissions" to "anon";

grant select on table "public"."auth_user_user_permissions" to "anon";

grant trigger on table "public"."auth_user_user_permissions" to "anon";

grant truncate on table "public"."auth_user_user_permissions" to "anon";

grant update on table "public"."auth_user_user_permissions" to "anon";

grant delete on table "public"."auth_user_user_permissions" to "authenticated";

grant insert on table "public"."auth_user_user_permissions" to "authenticated";

grant references on table "public"."auth_user_user_permissions" to "authenticated";

grant select on table "public"."auth_user_user_permissions" to "authenticated";

grant trigger on table "public"."auth_user_user_permissions" to "authenticated";

grant truncate on table "public"."auth_user_user_permissions" to "authenticated";

grant update on table "public"."auth_user_user_permissions" to "authenticated";

grant delete on table "public"."auth_user_user_permissions" to "service_role";

grant insert on table "public"."auth_user_user_permissions" to "service_role";

grant references on table "public"."auth_user_user_permissions" to "service_role";

grant select on table "public"."auth_user_user_permissions" to "service_role";

grant trigger on table "public"."auth_user_user_permissions" to "service_role";

grant truncate on table "public"."auth_user_user_permissions" to "service_role";

grant update on table "public"."auth_user_user_permissions" to "service_role";

grant delete on table "public"."django_admin_log" to "anon";

grant insert on table "public"."django_admin_log" to "anon";

grant references on table "public"."django_admin_log" to "anon";

grant select on table "public"."django_admin_log" to "anon";

grant trigger on table "public"."django_admin_log" to "anon";

grant truncate on table "public"."django_admin_log" to "anon";

grant update on table "public"."django_admin_log" to "anon";

grant delete on table "public"."django_admin_log" to "authenticated";

grant insert on table "public"."django_admin_log" to "authenticated";

grant references on table "public"."django_admin_log" to "authenticated";

grant select on table "public"."django_admin_log" to "authenticated";

grant trigger on table "public"."django_admin_log" to "authenticated";

grant truncate on table "public"."django_admin_log" to "authenticated";

grant update on table "public"."django_admin_log" to "authenticated";

grant delete on table "public"."django_admin_log" to "service_role";

grant insert on table "public"."django_admin_log" to "service_role";

grant references on table "public"."django_admin_log" to "service_role";

grant select on table "public"."django_admin_log" to "service_role";

grant trigger on table "public"."django_admin_log" to "service_role";

grant truncate on table "public"."django_admin_log" to "service_role";

grant update on table "public"."django_admin_log" to "service_role";

grant delete on table "public"."django_content_type" to "anon";

grant insert on table "public"."django_content_type" to "anon";

grant references on table "public"."django_content_type" to "anon";

grant select on table "public"."django_content_type" to "anon";

grant trigger on table "public"."django_content_type" to "anon";

grant truncate on table "public"."django_content_type" to "anon";

grant update on table "public"."django_content_type" to "anon";

grant delete on table "public"."django_content_type" to "authenticated";

grant insert on table "public"."django_content_type" to "authenticated";

grant references on table "public"."django_content_type" to "authenticated";

grant select on table "public"."django_content_type" to "authenticated";

grant trigger on table "public"."django_content_type" to "authenticated";

grant truncate on table "public"."django_content_type" to "authenticated";

grant update on table "public"."django_content_type" to "authenticated";

grant delete on table "public"."django_content_type" to "service_role";

grant insert on table "public"."django_content_type" to "service_role";

grant references on table "public"."django_content_type" to "service_role";

grant select on table "public"."django_content_type" to "service_role";

grant trigger on table "public"."django_content_type" to "service_role";

grant truncate on table "public"."django_content_type" to "service_role";

grant update on table "public"."django_content_type" to "service_role";

grant delete on table "public"."django_migrations" to "anon";

grant insert on table "public"."django_migrations" to "anon";

grant references on table "public"."django_migrations" to "anon";

grant select on table "public"."django_migrations" to "anon";

grant trigger on table "public"."django_migrations" to "anon";

grant truncate on table "public"."django_migrations" to "anon";

grant update on table "public"."django_migrations" to "anon";

grant delete on table "public"."django_migrations" to "authenticated";

grant insert on table "public"."django_migrations" to "authenticated";

grant references on table "public"."django_migrations" to "authenticated";

grant select on table "public"."django_migrations" to "authenticated";

grant trigger on table "public"."django_migrations" to "authenticated";

grant truncate on table "public"."django_migrations" to "authenticated";

grant update on table "public"."django_migrations" to "authenticated";

grant delete on table "public"."django_migrations" to "service_role";

grant insert on table "public"."django_migrations" to "service_role";

grant references on table "public"."django_migrations" to "service_role";

grant select on table "public"."django_migrations" to "service_role";

grant trigger on table "public"."django_migrations" to "service_role";

grant truncate on table "public"."django_migrations" to "service_role";

grant update on table "public"."django_migrations" to "service_role";

grant delete on table "public"."django_session" to "anon";

grant insert on table "public"."django_session" to "anon";

grant references on table "public"."django_session" to "anon";

grant select on table "public"."django_session" to "anon";

grant trigger on table "public"."django_session" to "anon";

grant truncate on table "public"."django_session" to "anon";

grant update on table "public"."django_session" to "anon";

grant delete on table "public"."django_session" to "authenticated";

grant insert on table "public"."django_session" to "authenticated";

grant references on table "public"."django_session" to "authenticated";

grant select on table "public"."django_session" to "authenticated";

grant trigger on table "public"."django_session" to "authenticated";

grant truncate on table "public"."django_session" to "authenticated";

grant update on table "public"."django_session" to "authenticated";

grant delete on table "public"."django_session" to "service_role";

grant insert on table "public"."django_session" to "service_role";

grant references on table "public"."django_session" to "service_role";

grant select on table "public"."django_session" to "service_role";

grant trigger on table "public"."django_session" to "service_role";

grant truncate on table "public"."django_session" to "service_role";

grant update on table "public"."django_session" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."removal"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable users to view their own data only"
on "public"."removal"
as permissive
for select
to authenticated
using (true);




