create type "public"."job_status" as enum ('queued', 'in_progress', 'completed', 'failed');

create table "public"."brokers" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "site_url" text,
    "enable_scraping" boolean default false,
    "scraping_url" text,
    "scraping_selector" text,
    "optout_url" text
);


alter table "public"."brokers" enable row level security;

create table "public"."jobs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "user" uuid default auth.uid(),
    "broker" bigint,
    "status" job_status,
    "result" jsonb
);


alter table "public"."jobs" enable row level security;

alter table "public"."users" drop column "avatar_url";

alter table "public"."users" drop column "full_name";

alter table "public"."users" add column "birth_date" date;

alter table "public"."users" add column "city" text;

alter table "public"."users" add column "first_name" text;

alter table "public"."users" add column "gender" smallint default '1'::smallint;

alter table "public"."users" add column "last_name" text;

alter table "public"."users" add column "state" text;

CREATE UNIQUE INDEX brokers_pkey ON public.brokers USING btree (id);

CREATE UNIQUE INDEX jobs_pkey ON public.jobs USING btree (id);

alter table "public"."brokers" add constraint "brokers_pkey" PRIMARY KEY using index "brokers_pkey";

alter table "public"."jobs" add constraint "jobs_pkey" PRIMARY KEY using index "jobs_pkey";

alter table "public"."jobs" add constraint "jobs_broker_fkey" FOREIGN KEY (broker) REFERENCES brokers(id) not valid;

alter table "public"."jobs" validate constraint "jobs_broker_fkey";

alter table "public"."jobs" add constraint "jobs_user_fkey" FOREIGN KEY ("user") REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."jobs" validate constraint "jobs_user_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.users (id)
  values (new.id);
  return new;
end;
$function$
;

grant delete on table "public"."brokers" to "anon";

grant insert on table "public"."brokers" to "anon";

grant references on table "public"."brokers" to "anon";

grant select on table "public"."brokers" to "anon";

grant trigger on table "public"."brokers" to "anon";

grant truncate on table "public"."brokers" to "anon";

grant update on table "public"."brokers" to "anon";

grant delete on table "public"."brokers" to "authenticated";

grant insert on table "public"."brokers" to "authenticated";

grant references on table "public"."brokers" to "authenticated";

grant select on table "public"."brokers" to "authenticated";

grant trigger on table "public"."brokers" to "authenticated";

grant truncate on table "public"."brokers" to "authenticated";

grant update on table "public"."brokers" to "authenticated";

grant delete on table "public"."brokers" to "service_role";

grant insert on table "public"."brokers" to "service_role";

grant references on table "public"."brokers" to "service_role";

grant select on table "public"."brokers" to "service_role";

grant trigger on table "public"."brokers" to "service_role";

grant truncate on table "public"."brokers" to "service_role";

grant update on table "public"."brokers" to "service_role";

grant delete on table "public"."jobs" to "anon";

grant insert on table "public"."jobs" to "anon";

grant references on table "public"."jobs" to "anon";

grant select on table "public"."jobs" to "anon";

grant trigger on table "public"."jobs" to "anon";

grant truncate on table "public"."jobs" to "anon";

grant update on table "public"."jobs" to "anon";

grant delete on table "public"."jobs" to "authenticated";

grant insert on table "public"."jobs" to "authenticated";

grant references on table "public"."jobs" to "authenticated";

grant select on table "public"."jobs" to "authenticated";

grant trigger on table "public"."jobs" to "authenticated";

grant truncate on table "public"."jobs" to "authenticated";

grant update on table "public"."jobs" to "authenticated";

grant delete on table "public"."jobs" to "service_role";

grant insert on table "public"."jobs" to "service_role";

grant references on table "public"."jobs" to "service_role";

grant select on table "public"."jobs" to "service_role";

grant trigger on table "public"."jobs" to "service_role";

grant truncate on table "public"."jobs" to "service_role";

grant update on table "public"."jobs" to "service_role";

create policy "Enable read for authenticated users only"
on "public"."brokers"
as permissive
for select
to authenticated
using (true);


create policy "Enable insert for authenticated users only"
on "public"."jobs"
as permissive
for insert
to authenticated
with check (true);


create policy "users can update own data"
on "public"."jobs"
as permissive
for update
to public
using ((auth.uid() = "user"));


create policy "users can view own data"
on "public"."jobs"
as permissive
for select
to public
using ((auth.uid() = "user"));




