create table "public"."google" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile_id" bigint,
    "status" search_status,
    "result" jsonb,
    "user_id" uuid,
    "updated_at" timestamp with time zone default now()
);


alter table "public"."google" enable row level security;

CREATE UNIQUE INDEX google_pkey ON public.google USING btree (id);

alter table "public"."google" add constraint "google_pkey" PRIMARY KEY using index "google_pkey";

alter table "public"."google" add constraint "google_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."google" validate constraint "google_profile_id_fkey";

alter table "public"."google" add constraint "google_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."google" validate constraint "google_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_search_queue()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
  INSERT INTO search (broker_id, user_id, profile_id, status)
  SELECT brokers.id, NEW.user_id, NEW.id, 'queued'
  FROM brokers;

  INSERT INTO google (user_id, profile_id, status)
  VALUES (NEW.user_id, NEW.id, 'queued');

  RETURN NEW;
END;$function$
;

grant delete on table "public"."google" to "anon";

grant insert on table "public"."google" to "anon";

grant references on table "public"."google" to "anon";

grant select on table "public"."google" to "anon";

grant trigger on table "public"."google" to "anon";

grant truncate on table "public"."google" to "anon";

grant update on table "public"."google" to "anon";

grant delete on table "public"."google" to "authenticated";

grant insert on table "public"."google" to "authenticated";

grant references on table "public"."google" to "authenticated";

grant select on table "public"."google" to "authenticated";

grant trigger on table "public"."google" to "authenticated";

grant truncate on table "public"."google" to "authenticated";

grant update on table "public"."google" to "authenticated";

grant delete on table "public"."google" to "service_role";

grant insert on table "public"."google" to "service_role";

grant references on table "public"."google" to "service_role";

grant select on table "public"."google" to "service_role";

grant trigger on table "public"."google" to "service_role";

grant truncate on table "public"."google" to "service_role";

grant update on table "public"."google" to "service_role";

create policy "Can view own data"
on "public"."google"
as permissive
for select
to public
using ((auth.uid() = user_id));


create policy "Enable insert for users based on user_id"
on "public"."google"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = user_id));




