-- Create feedback_responses table
create table "public"."feedback_responses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "question_1_response" text,
    "question_2_response" text,
    "question_3_response" text,
    "question_4_response" text,
    "question_5_response" text,
    "question_6_response" text,
    "question_7_response" text
);

-- Add primary key constraint
CREATE UNIQUE INDEX feedback_responses_pkey ON public.feedback_responses USING btree (id);
alter table "public"."feedback_responses" add constraint "feedback_responses_pkey" PRIMARY KEY using index "feedback_responses_pkey";

-- Create index for created_at
create index feedback_responses_created_at_idx on public.feedback_responses using btree (created_at);

-- Grant permissions
grant insert on table "public"."feedback_responses" to "anon";
grant insert on table "public"."feedback_responses" to "authenticated";
grant all on table "public"."feedback_responses" to "service_role";
