drop policy "Enable insert for authenticated users only" on "public"."searches";

drop policy "Enable users to view their own data only" on "public"."searches";

revoke delete on table "public"."searches" from "anon";

revoke insert on table "public"."searches" from "anon";

revoke references on table "public"."searches" from "anon";

revoke select on table "public"."searches" from "anon";

revoke trigger on table "public"."searches" from "anon";

revoke truncate on table "public"."searches" from "anon";

revoke update on table "public"."searches" from "anon";

revoke delete on table "public"."searches" from "authenticated";

revoke insert on table "public"."searches" from "authenticated";

revoke references on table "public"."searches" from "authenticated";

revoke select on table "public"."searches" from "authenticated";

revoke trigger on table "public"."searches" from "authenticated";

revoke truncate on table "public"."searches" from "authenticated";

revoke update on table "public"."searches" from "authenticated";

revoke delete on table "public"."searches" from "service_role";

revoke insert on table "public"."searches" from "service_role";

revoke references on table "public"."searches" from "service_role";

revoke select on table "public"."searches" from "service_role";

revoke trigger on table "public"."searches" from "service_role";

revoke truncate on table "public"."searches" from "service_role";

revoke update on table "public"."searches" from "service_role";

alter table "public"."searches" drop constraint "broker_searches_broker_id_fkey";

alter table "public"."searches" drop constraint "broker_searches_profile_id_fkey";

alter table "public"."searches" drop constraint "broker_searches_pkey";

drop index if exists "public"."broker_searches_pkey";

drop table "public"."searches";

create table "public"."broker_searches" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "profile_id" bigint,
    "broker_id" bigint,
    "search_status" search_status,
    "search_result" jsonb,
    "removal_status" removal_status,
    "removal_note" text,
    "version" text
);


alter table "public"."broker_searches" enable row level security;

create table "public"."google_searches" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "profile_id" bigint,
    "search_status" search_status,
    "search_result" jsonb,
    "removal_status" removal_status,
    "removal_note" text,
    "version" text
);


alter table "public"."google_searches" enable row level security;

CREATE UNIQUE INDEX google_scans_pkey ON public.google_searches USING btree (id);

CREATE UNIQUE INDEX broker_searches_pkey ON public.broker_searches USING btree (id);

alter table "public"."broker_searches" add constraint "broker_searches_pkey" PRIMARY KEY using index "broker_searches_pkey";

alter table "public"."google_searches" add constraint "google_scans_pkey" PRIMARY KEY using index "google_scans_pkey";

alter table "public"."broker_searches" add constraint "broker_searches_broker_id_fkey" FOREIGN KEY (broker_id) REFERENCES brokers(id) not valid;

alter table "public"."broker_searches" validate constraint "broker_searches_broker_id_fkey";

alter table "public"."broker_searches" add constraint "broker_searches_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) not valid;

alter table "public"."broker_searches" validate constraint "broker_searches_profile_id_fkey";

alter table "public"."google_searches" add constraint "google_scans_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) not valid;

alter table "public"."google_searches" validate constraint "google_scans_profile_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_search_queue()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
  INSERT INTO broker_searches (profile_id, broker_id, search_status)
  SELECT NEW.id, brokers.id, 'queued'
  FROM brokers;

  INSERT INTO google_searches (profile_id, search_status)
  VALUES (NEW.id, 'queued');

  RETURN NEW;
END;$function$
;

grant delete on table "public"."broker_searches" to "anon";

grant insert on table "public"."broker_searches" to "anon";

grant references on table "public"."broker_searches" to "anon";

grant select on table "public"."broker_searches" to "anon";

grant trigger on table "public"."broker_searches" to "anon";

grant truncate on table "public"."broker_searches" to "anon";

grant update on table "public"."broker_searches" to "anon";

grant delete on table "public"."broker_searches" to "authenticated";

grant insert on table "public"."broker_searches" to "authenticated";

grant references on table "public"."broker_searches" to "authenticated";

grant select on table "public"."broker_searches" to "authenticated";

grant trigger on table "public"."broker_searches" to "authenticated";

grant truncate on table "public"."broker_searches" to "authenticated";

grant update on table "public"."broker_searches" to "authenticated";

grant delete on table "public"."broker_searches" to "service_role";

grant insert on table "public"."broker_searches" to "service_role";

grant references on table "public"."broker_searches" to "service_role";

grant select on table "public"."broker_searches" to "service_role";

grant trigger on table "public"."broker_searches" to "service_role";

grant truncate on table "public"."broker_searches" to "service_role";

grant update on table "public"."broker_searches" to "service_role";

grant delete on table "public"."google_searches" to "anon";

grant insert on table "public"."google_searches" to "anon";

grant references on table "public"."google_searches" to "anon";

grant select on table "public"."google_searches" to "anon";

grant trigger on table "public"."google_searches" to "anon";

grant truncate on table "public"."google_searches" to "anon";

grant update on table "public"."google_searches" to "anon";

grant delete on table "public"."google_searches" to "authenticated";

grant insert on table "public"."google_searches" to "authenticated";

grant references on table "public"."google_searches" to "authenticated";

grant select on table "public"."google_searches" to "authenticated";

grant trigger on table "public"."google_searches" to "authenticated";

grant truncate on table "public"."google_searches" to "authenticated";

grant update on table "public"."google_searches" to "authenticated";

grant delete on table "public"."google_searches" to "service_role";

grant insert on table "public"."google_searches" to "service_role";

grant references on table "public"."google_searches" to "service_role";

grant select on table "public"."google_searches" to "service_role";

grant trigger on table "public"."google_searches" to "service_role";

grant truncate on table "public"."google_searches" to "service_role";

grant update on table "public"."google_searches" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."broker_searches"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) IN ( SELECT profiles.user_id
   FROM profiles
  WHERE (profiles.id = broker_searches.profile_id))));


create policy "Enable users to view their own data only"
on "public"."broker_searches"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) IN ( SELECT profiles.user_id
   FROM profiles
  WHERE (profiles.id = broker_searches.profile_id))));




