drop policy "Enable users to view their own data only" on "public"."pricing_plans";

alter table "public"."pricing_plans" drop constraint "pricing_plans_profile_id_fkey";

alter table "public"."pricing_plans" drop constraint "pricing_plans_pkey";

drop index if exists "public"."pricing_plans_pkey";

create table "public"."settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "receive_status_updates" text,
    "receive_marketing_emails" boolean,
    "allow_multi_device_login" boolean,
    "deleted" boolean,
    "require_multi_factor_verification" boolean
);


alter table "public"."settings" enable row level security;

alter table "public"."pricing_plans" drop column "profile_id";

alter table "public"."pricing_plans" add column "user_id" uuid;

alter table "public"."profiles" add column "address" text;

alter table "public"."profiles" add column "alternative_names" text;

alter table "public"."profiles" add column "bio" text;

alter table "public"."profiles" add column "email" text;

alter table "public"."profiles" add column "isPrimary" boolean;

alter table "public"."profiles" add column "phone" text;

alter table "public"."profiles" add column "social_security_number" text;

CREATE UNIQUE INDEX plans_pkey ON public.pricing_plans USING btree (id);

alter table "public"."pricing_plans" add constraint "plans_pkey" PRIMARY KEY using index "plans_pkey";

alter table "public"."pricing_plans" add constraint "plans_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."pricing_plans" validate constraint "plans_user_id_fkey";

alter table "public"."settings" add constraint "settings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."settings" validate constraint "settings_user_id_fkey";

grant delete on table "public"."settings" to "anon";

grant insert on table "public"."settings" to "anon";

grant references on table "public"."settings" to "anon";

grant select on table "public"."settings" to "anon";

grant trigger on table "public"."settings" to "anon";

grant truncate on table "public"."settings" to "anon";

grant update on table "public"."settings" to "anon";

grant delete on table "public"."settings" to "authenticated";

grant insert on table "public"."settings" to "authenticated";

grant references on table "public"."settings" to "authenticated";

grant select on table "public"."settings" to "authenticated";

grant trigger on table "public"."settings" to "authenticated";

grant truncate on table "public"."settings" to "authenticated";

grant update on table "public"."settings" to "authenticated";

grant delete on table "public"."settings" to "service_role";

grant insert on table "public"."settings" to "service_role";

grant references on table "public"."settings" to "service_role";

grant select on table "public"."settings" to "service_role";

grant trigger on table "public"."settings" to "service_role";

grant truncate on table "public"."settings" to "service_role";

grant update on table "public"."settings" to "service_role";

create policy "Enable insert for users based on user_id"
on "public"."pricing_plans"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable users to view their own data only"
on "public"."pricing_plans"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));




