-- Create login_history table
create table "public"."login_history" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "device_type" text,
    "user_agent" text,
    "location" jsonb,
    "success" boolean not null default true
);

-- Enable RLS
alter table "public"."login_history" enable row level security;

-- Create indexes for better query performance
create index login_history_user_id_idx on public.login_history using btree (user_id);
create index login_history_created_at_idx on public.login_history using btree (created_at);

-- Set up RLS policies
create policy "Users can view their own login history"
on public.login_history for select
to authenticated
using (auth.uid() = user_id);

create policy "Insert allowed for service role only"
on public.login_history for insert
to service_role
with check (true);

-- Add primary key constraint
CREATE UNIQUE INDEX login_history_pkey ON public.login_history USING btree (id);

alter table "public"."login_history" add constraint "login_history_pkey" PRIMARY KEY using index "login_history_pkey";

-- Add foreign key constraint
alter table "public"."login_history" add constraint "login_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."login_history" validate constraint "login_history_user_id_fkey";

-- Grant permissions for anon
grant delete on table "public"."login_history" to "anon";

grant insert on table "public"."login_history" to "anon";

grant references on table "public"."login_history" to "anon";

grant select on table "public"."login_history" to "anon";

grant trigger on table "public"."login_history" to "anon";

grant truncate on table "public"."login_history" to "anon";

grant update on table "public"."login_history" to "anon";

-- Grant permissions for authenticated
grant delete on table "public"."login_history" to "authenticated";

grant insert on table "public"."login_history" to "authenticated";

grant references on table "public"."login_history" to "authenticated";

grant select on table "public"."login_history" to "authenticated";

grant trigger on table "public"."login_history" to "authenticated";

grant truncate on table "public"."login_history" to "authenticated";

grant update on table "public"."login_history" to "authenticated";

-- Grant permissions for service_role
grant delete on table "public"."login_history" to "service_role";

grant insert on table "public"."login_history" to "service_role";

grant references on table "public"."login_history" to "service_role";

grant select on table "public"."login_history" to "service_role";

grant trigger on table "public"."login_history" to "service_role";

grant truncate on table "public"."login_history" to "service_role";

grant update on table "public"."login_history" to "service_role";
