drop trigger if exists "broker_search_queued" on "public"."broker_searches";

drop trigger if exists "google_search_queued" on "public"."google_searches";

create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "name" text,
    "email" text,
    "message" text
);


alter table "public"."messages" enable row level security;

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."messages" add constraint "messages_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."messages" validate constraint "messages_user_id_fkey";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

CREATE TRIGGER broker_search_queued AFTER INSERT ON public.broker_searches FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://major-rockets-run.loca.lt/scan/broker', 'POST', '{"Content-type":"application/json"}', '{}', '10000');

CREATE TRIGGER google_search_queued AFTER INSERT ON public.google_searches FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://major-rockets-run.loca.lt/scan/google', 'POST', '{"Content-type":"application/json"}', '{}', '10000');



