-- Create feedback_responses table
create table "public"."feedback_responses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "question_1_response" text,
    "question_2_response" text,
    "question_3_response" text,
    "question_4_response" text,
    "question_5_response" text,
    "question_6_response" text
);

-- Enable RLS
alter table "public"."feedback_responses" enable row level security;

-- Create indexes
create index feedback_responses_user_id_idx on public.feedback_responses using btree (user_id);
create index feedback_responses_created_at_idx on public.feedback_responses using btree (created_at);

-- Set up RLS policy for insertion only
create policy "Anyone can submit feedback"
on public.feedback_responses for insert
to public
with check (true);

-- Add primary key constraint
CREATE UNIQUE INDEX feedback_responses_pkey ON public.feedback_responses USING btree (id);
alter table "public"."feedback_responses" add constraint "feedback_responses_pkey" PRIMARY KEY using index "feedback_responses_pkey";

-- Add foreign key constraint
alter table "public"."feedback_responses" add constraint "feedback_responses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;
alter table "public"."feedback_responses" validate constraint "feedback_responses_user_id_fkey";

-- Grant permissions
grant insert on table "public"."feedback_responses" to "anon";
grant insert on table "public"."feedback_responses" to "authenticated";
grant all on table "public"."feedback_responses" to "service_role";
